let data = {
  "status": "success",
  "totalResults": 4295,
  "results": [
    {
      "article_id": "acbb9037fe7117d9ce44dae4e61a1388",
      "title": "It looks like AMD's expecting the RX 9070 XT to rival the RTX 4070 Ti, which is fine if it ends up being the right price",
      "link": "https://www.pcgamer.com/hardware/graphics-cards/it-looks-like-amds-expecting-the-rx-9070-xt-to-rival-the-rtx-4070-ti-which-is-fine-if-it-ends-up-being-the-right-price/",
      "keywords": ["graphics cards", "hardware"],
      "creator": null,
      "video_url": null,
      "description": "It's all about the money, money, money.",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:47:00",
      "pubDateTZ": "UTC",
      "image_url": "https://cdn.mos.cms.futurecdn.net/JHSQsWNyrqdpGqkivr5pyT.jpg",
      "source_id": "pcgamer",
      "source_priority": 3730,
      "source_name": "Pc Gamer",
      "source_url": "https://www.pcgamer.com",
      "source_icon": "https://i.bytvi.com/domain_icons/pcgamer.png",
      "language": "english",
      "country": [
        "united kingdom",
        "australia",
        "canada",
        "united states of america"
      ],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "638cdf9613e8fbd32e5b7b926190fbf3",
      "title": "AMD Ryzen AI Max is finally here: 'the most advanced mobile x86 processor ever created' with 40 RDNA 3.5 CUs and 16 Zen 5 cores",
      "link": "https://www.pcgamer.com/hardware/processors/amd-ryzen-ai-max-is-finally-here-the-most-advanced-mobile-x86-processor-ever-created-with-40-rdna-3-5-cus-and-16-zen-5-cores/",
      "keywords": ["processors", "hardware"],
      "creator": null,
      "video_url": null,
      "description": "Strix Halo has finally arrived.",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:47:00",
      "pubDateTZ": "UTC",
      "image_url": "https://cdn.mos.cms.futurecdn.net/VCkwq2FV7M7bUiVenTvcmb.jpg",
      "source_id": "pcgamer",
      "source_priority": 3730,
      "source_name": "Pc Gamer",
      "source_url": "https://www.pcgamer.com",
      "source_icon": "https://i.bytvi.com/domain_icons/pcgamer.png",
      "language": "english",
      "country": [
        "united kingdom",
        "australia",
        "canada",
        "united states of america"
      ],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "4010404c603f120b7fa58e420fecc3a4",
      "title": "AMD Announces Expanded Consumer and Commercial AI PC Portfolio at CES - GlobeNewswire",
      "link": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxOOUVzVHpIUGE3ZmVjaFhVSG1GbHl0M1pGT0xJN0hfM2xkZktBQTlVTG8zQmJBbmlDS1BKVm9qd3JZNXJZWXBPaHJ3cm5aYy1KZzdnZ210Ty02aWtQTE1YZEdvYWpnWkVuaDBCWmtTSjd4OU9mdnZXSkVtNF90MTNicDV6cUlsOG5LWU9ZLU9iaGpMN3NQaEdmMzNiNFgzWGp0cUVDYlpCTzhkYk1BVUFETWtNbnNKcVdqQ0QzcmdHYkVlVDVacmMyVVBsNXVmQlY2YlBoYUV6RjQ?oc=5",
      "keywords": null,
      "creator": null,
      "video_url": null,
      "description": "AMD Announces Expanded Consumer and Commercial AI PC Portfolio at CES GlobeNewswireCES 2025: Intel, AMD, and NVIDIA gear up to shape computing’s next big leap DigitAMD Ryzen 9 9950X3D & 9900X3D “3D V-Cache” CPUs Official: Up To 5.7 GHz Clock, 144 MB Cache & 64% Faster Than Intel 285K WccftechAMD launches Ryzen 9000HX \"Fire Range\" mobile CPU series, up to 16 Zen5 cores and 140MB cache VideoCardz.comAMD’s Ryzen 9 9950X3D is ‘the world’s best processor for gamers and creators’ The Verge",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:48",
      "pubDateTZ": "UTC",
      "image_url": null,
      "source_id": "google",
      "source_priority": 14,
      "source_name": "Google News",
      "source_url": "https://news.google.com",
      "source_icon": "https://i.bytvi.com/domain_icons/google.png",
      "language": "english",
      "country": ["india"],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "6f3ca3a050f46d8f9a7c34cade49c512",
      "title": "Acer Levels Up Mobile Gaming at CES 2025 with New Nitro V Laptops and Blaze Handhelds",
      "link": "https://www.yankodesign.com/2025/01/06/acer-levels-up-mobile-gaming-at-ces-2025-with-new-nitro-v-laptops-and-blaze-handhelds/",
      "keywords": [
        "laptops",
        "controllers",
        "acer",
        "events",
        "gaming",
        "accessories",
        "ces 2025",
        "ces",
        "handheld gaming",
        "gadgets"
      ],
      "creator": ["JC Torres"],
      "video_url": null,
      "description": "Acer Levels Up Mobile Gaming at CES 2025 with New Nitro V Laptops and Blaze HandheldsPC gaming used to mean being glued to your chair and desk at home, but times have quickly changed for the past years. In addition...",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:43",
      "pubDateTZ": "UTC",
      "image_url": "https://www.yankodesign.com/images/design_news/2025/01/acer-levels-up-mobile-gaming-at-ces-2025-with-new-nitro-v-laptops-and-blaze-handhelds/acer-ces-2025-nitro-blaze-8-02.jpg",
      "source_id": "yankodesign",
      "source_priority": 22224,
      "source_name": "Yanko Design",
      "source_url": "https://www.yankodesign.com",
      "source_icon": "https://i.bytvi.com/domain_icons/yankodesign.png",
      "language": "english",
      "country": ["canada"],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "7868f1db0744f42b7971cc4ea2adc4f4",
      "title": "Acer's new Aspire Vero 16 is made partially with oyster shells",
      "link": "https://www.androidheadlines.com/2025/01/acers-new-aspire-vero-16-is-made-partially-with-oyster-shells.html",
      "keywords": [
        "ces",
        "acer aspire vero 16",
        "mobile events news",
        "tech news",
        "laptops",
        "acer",
        "all the latest android & tech news",
        "acer swift go"
      ],
      "creator": ["Justin Diaz"],
      "video_url": null,
      "description": "The post Acer's new Aspire Vero 16 is made partially with oyster shells appeared first on Android Headlines.",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:31",
      "pubDateTZ": "UTC",
      "image_url": "https://www.androidheadlines.com/wp-content/uploads/2025/01/Acer-Aspire-Vero-16-1420x1136.webp",
      "source_id": "androidheadlines",
      "source_priority": 140907,
      "source_name": "Androidheadlines",
      "source_url": "https://www.androidheadlines.com",
      "source_icon": "https://i.bytvi.com/domain_icons/androidheadlines.png",
      "language": "english",
      "country": ["united states of america", "canada"],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "65a41277d679e602f9f93a6578bcd749",
      "title": "From bizarre furry robots that cling onto your bag to the world’s ‘first’ electric skates – the gadgets so far at CES",
      "link": "https://www.the-sun.com/tech/13232546/ces-2025-weird-furry-robot-worlds-first-electric-skates/",
      "keywords": ["longtail", "artificial intelligence", "robots", "tech"],
      "creator": ["Jamie Harris"],
      "video_url": null,
      "description": null,
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:31",
      "pubDateTZ": "UTC",
      "image_url": "https://www.the-sun.com/wp-content/uploads/sites/6/2025/01/newspress-collage-s2yhv4pwk-1736192681041.jpg?crop=1&h=1080&quality=100&strip=all&w=1920",
      "source_id": "thesun",
      "source_priority": 1813,
      "source_name": "The Sun",
      "source_url": "https://www.thesun.co.uk",
      "source_icon": "https://i.bytvi.com/domain_icons/thesun.png",
      "language": "english",
      "country": ["united states of america"],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": true
    },
    {
      "article_id": "1eb94ec5ec75eee98201119181d56cd4",
      "title": "AMD announces more powerful Ryzen Z2 Series processors for future PC handhelds, but Valve says 'There is and will be no Z2 Steam Deck'",
      "link": "https://www.pcgamer.com/hardware/handheld-gaming-pcs/a-new-steam-deck-is-coming-with-one-of-amds-more-powerful-ryzen-z2-series-processors-inside-it/",
      "keywords": ["handheld gaming pcs", "hardware"],
      "creator": null,
      "video_url": null,
      "description": "AMD has confirmed that Valve will be using one of its latest processors, the Z2 Series, inside a new Steam Deck. As will Asus and Lenovo.",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:30",
      "pubDateTZ": "UTC",
      "image_url": "https://cdn.mos.cms.futurecdn.net/Coph5tP2BPCHLz4dv9SCEj.jpg",
      "source_id": "pcgamer",
      "source_priority": 3730,
      "source_name": "Pc Gamer",
      "source_url": "https://www.pcgamer.com",
      "source_icon": "https://i.bytvi.com/domain_icons/pcgamer.png",
      "language": "english",
      "country": [
        "united kingdom",
        "australia",
        "canada",
        "united states of america"
      ],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "4d7e41ef3bf25f8b8ab8e260d926e2ec",
      "title": "AMD just gave us our first look at the Radeon RX 9070 XT and RX 9070 RDNA 4 GPUs and I am officially whelmed",
      "link": "https://www.pcgamer.com/hardware/amd-just-gave-us-our-first-look-at-the-radeon-rx-9070-xt-and-rx-9070-rdna-4-gpus-and-i-am-officially-whelmed/",
      "keywords": ["graphics cards", "hardware"],
      "creator": null,
      "video_url": null,
      "description": "A preview rather than a full-on announcement, but it's a brief look at the next-gen GPU competition at least.",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:10",
      "pubDateTZ": "UTC",
      "image_url": "https://cdn.mos.cms.futurecdn.net/FbucRiSjc8TZnXzYoMo2FF.jpg",
      "source_id": "pcgamer",
      "source_priority": 3730,
      "source_name": "Pc Gamer",
      "source_url": "https://www.pcgamer.com",
      "source_icon": "https://i.bytvi.com/domain_icons/pcgamer.png",
      "language": "english",
      "country": [
        "united kingdom",
        "australia",
        "canada",
        "united states of america"
      ],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "c79771002262b5293786ba184397d76e",
      "title": "AMD Announces New Graphics and Gaming Products for Ultimate Gameplay Experience at CES - Marketscreener.com",
      "link": "https://news.google.com/rss/articles/CBMiiwJBVV95cUxPd0xyeHVJYmFOOGI4Z1NPLS1HbHFkcVJWWUpwVWtmSGZKbk9xNi0wbmF3a3ZHYXBFS2t5UTJGVkRxUXhpQUJBY1REd2NGU3hfNFAyOUV6S2FGX0ZFeUJoLWh6MElHLTBaRXo4bVByQ3lvbThJVzJZamdLT1U1YXgxNXJnM09QOUVPUFdSR3E0WVAwSzJDeldzZTQ1QUNFaUNmbXI4d3NiTXpiSUdhR2hmNGRtZ05mdE9LNGd3MVc0SGwzeWtrTkloSU1yVnpUZFRGOHpOLXRXbmp1U0NVYi04a2M0M3hqZGFqM3dUejI2bGllanF6OG9sR3RxR1h2Zy1zV05HRDl1eWVSSlU?oc=5",
      "keywords": null,
      "creator": null,
      "video_url": null,
      "description": "AMD Announces New Graphics and Gaming Products for Ultimate Gameplay Experience at CES Marketscreener.comHow to watch the CES 2025 Nvidia keynote livestream today MashableAMD Adds Dell as Commercial PC Customer for the First Time BloombergAMD Ryzen 9 9950X3D officially outpaces 7950X3D by 8% and Intel 285K by 20% in gaming VideoCardz.comWatch The AMD CES 2025 Event Live Here: RDNA 4 GPUs, Ryzen 9000 Desktop & Laptop CPUs, FSR 4 & More Wccftech",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:06",
      "pubDateTZ": "UTC",
      "image_url": null,
      "source_id": "google",
      "source_priority": 14,
      "source_name": "Google News",
      "source_url": "https://news.google.com",
      "source_icon": "https://i.bytvi.com/domain_icons/google.png",
      "language": "english",
      "country": ["singapore"],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    },
    {
      "article_id": "d81d5ef93e8243046dc2800f74dbb5dd",
      "title": "CES 2025 | Dell unveils simplified AI-Powered PC lineup, new accessories",
      "link": "https://www.cnbctv18.com/technology/ces-2025-dell-new-ai-powered-pc-portfolio-19535447.htm",
      "keywords": ["technology"],
      "creator": ["CNBCTV18"],
      "video_url": null,
      "description": "At CES 2025, Dell unveiled a streamlined AI-powered PC lineup with a unified branding and featuring enhanced performance, sustainability, modular designs, and AI capabilities.",
      "content": "ONLY AVAILABLE IN PAID PLANS",
      "pubDate": "2025-01-06 19:46:02",
      "pubDateTZ": "UTC",
      "image_url": "https://images.cnbctv18.com/uploads/2025/01/dell-ces-2025-2025-01-bcd9fbae0e499a8274d7e0f2cafbcbf0.jpeg",
      "source_id": "cnbctv18",
      "source_priority": 17950,
      "source_name": "Cnbctv18",
      "source_url": "https://www.cnbctv18.com",
      "source_icon": "https://i.bytvi.com/domain_icons/cnbctv18.jpg",
      "language": "english",
      "country": ["india"],
      "category": ["technology"],
      "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
      "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
      "duplicate": false
    }
  ],
  "nextPage": "1736192762197383344"
}

export default data